### PR TITLE
Remove CSS for compatibility

### PR DESCRIPTION
**Pull request by r-gaia-cs**
In the spirit of "one image worth a thousand words":

s

On the left is the one of the presentations from https://github.com/swcarpentry/slideshows and on the right is the motivation slide.

**Important:** I didn't commit `motivation.html`. You will need to run `make preview`.

### CODE REVIEW

**Comment by r-gaia-cs** [comment]
I removed a few more lines and the it should be more like the ones in slideshows.

**Comment by gvwilson** [comment]
Thanks @r-gaia-cs but:

1. When I run `make preview` and then open `motivation.html`, I get this error message:

screen shot 2015-01-21 at 2 49 21 pm

2. How do I cherry-pick just this change back into the `core` branch?  I don't want to accidentally bring over all the example HTML files into `core`.  (I'm more and more inclined to make `core` a separate repository.)

**Comment by r-gaia-cs** [comment]
> How do I cherry-pick just this change back into the core branch? I don't want to accidentally bring over all the example HTML files into core. (I'm more and more inclined to make core a separate repository.)

~~~
$ git checkout core
$ git checkout -b improve-slide
$ git cherry-pick -n 9957c25
$ git rm motivation.*
$ git commit
$ git cherry-pick db8880f
$ git cherry-pick a2228b3
~~~

I hope this is what you looking for.

**Comment by gvwilson** [comment]
Thanks - can you please check the 'core' branch of 
http://github.com/gvwilson/lesson-template ?  If it looks OK, I'll PR to 
swcarpentry/lesson-template, merge to gh-pages, etc.

**Comment by r-gaia-cs** [comment]
> can you please check the 'core' branch of http://github.com/gvwilson/lesson-template

The commit message of 2898c67 should be

~~~
Import style for slides from https://github.com/swcarpentry/slideshows
~~~

or something close to it.

Otherwise this looks good.

**Pull request merged**
